---
abstract: 'Serve static files with HTTP::Server::Simple'
author:
  - 'Stephen Quinney <sjq-perl@jadevine.org.uk>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Server-Simple-Static
provides:
  HTTP::Server::Simple::Static:
    file: lib/HTTP/Server/Simple/Static.pm
    version: 0.09
requires:
  CGI: 3.46
  Exporter: 0
  File::LibMagic: 0
  File::Spec::Functions: 0
  HTTP::Date: 0
  HTTP::Server::Simple: 0.01
  IO::File: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
