--- #YAML:1.0
name: HTTP-Server-Simple-Static
version: 0.01
author:
  - |-
    Marcus Ramberg C<marcus@thefeed.no>
    Thanks to Simon Cozens for initial implementation.
abstract: Serve static files with HTTP::Server::Simple
license: perl
requires:
  Exporter: 0
  File::MMagic: 0
  File::Spec::Functions: 0
  HTTP::Server::Simple: 0.01
  MIME::Types: 0
  URI::Escape: 0
provides:
  HTTP::Server::Simple::Static:
    file: lib/HTTP/Server/Simple/Static.pm
    version: 0.01
generated_by: Module::Build version 0.25
